spring:
  application:
    name: lms

  datasource:
    url: jdbc:mysql://localhost:3306/blog?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Zcy520521

  jpa:
#    generate-ddl: true
    show-sql: true
#  security:
#    user:
#      name: 'zcy0052800@1'
#      password: 'zcy521'

  mail:
    host: localhost
    port: 1025

my:
  admin:
    admin-page-content-list:
      - name: 'dashboard'
        description: "/admin/dashboard"
        data : 'tachometer-alt'
      - name: 'users'
        description: "/admin/users"
        data: 'users'
      - name: "blogs"
        description: "/admin/blogs"
        data: "file-alt"
